CREATE TABLE TB_LOV_TEST(
PROD_CODE VARCHAR2 (100),
DESRC VARCHAR2 (888));
INSERT INTO TB_LOV_TEST VALUES ('ACCO','PRODUKTI I PARE');
INSERT INTO TB_LOV_TEST VALUES ('AMEX','PRODUKTI I DYTE');
SELECT PROD_CODE, DESRC FROM TB_LOV_TEST;
