
create TABLE STTM_DTES2
(CUST_CAT varchar2(199),

CUST_ID varchar2(35),
CUST_TYPE varchar2(35),
FIELD_DES varchar2(35),
MANDATORY_VALIDATION  varchar2(35),
CONSTRAINT PX_STTM_DTES2  PRIMARY KEY (CUST_TYPE,CUST_ID,FIELD_DES)

);
