create TABLE STTM_DETAIL_SUS3 
(
CUST_ID_DET varchar2(35),
TEMP VARCHAR2(35),
FIELD_DES varchar2(35),
MANDATORY_VALIDATION  varchar2(35),
CONSTRAINT PX_STTM_DETAIL_SUS3  PRIMARY KEY (CUST_ID_DET,TEMP)

);
