CREATE OR REPLACE FUNCTION BS_FN_RATE_FCUST (P_BRANCH_CODE in varchar2, P_CURR_FIRST IN VARCHAR2, P_CURR_LAST IN VARCHAR2) RETURN NUMBER IS l_MID NUMBER;
--KY FUNKSION SYNON TE LLOGARISI MONEDHAT E DERIVUARA 
--PRANDAJ MBAJME DISA VAR TEMP TE CILET DO TE FUNKSIONOJNE PER TE LLOGARITUR MID RATET E NDERMJETME.
l_temp_res number;
l_temp_res1 number;
l_temp_res2 number;
l_temp_res3 number;--MBAJME DISA VARIABLA TE CILET DO SHERBEJNE PER RETRIVE NGA TABELAT DHE DISA TE RUAJNE GJENDJET TEMPORARE TE MONEDHAVE
L_MONEDHA_E_PARE VARCHAR2 (5);
TAB_L_MONEDHA_E_PARE VARCHAR2  (5);
TAB_L_MONEDHA_E_DYTE1 VARCHAR2  (5);
L_MONEDHA_E_DYTE VARCHAR2 (5);
TAB_L_MONEDHA_E_DYTE VARCHAR2 (5);
COM_MON VARCHAR2 (5);
--COUNTERS DO TE NA SHERBEJNE PER TE KONTROLLUAR EKZISTENCEN E MONEDHAVE NE GJENDJET E COL
 COUNTER  NUMBER;
 COUNTER1  NUMBER;
  COUNTER5  NUMBER := 1;
begin
--KONTROLLOJME NE QOFTE SE MONEDHAT KANE MARREDHENIE TE DREJTEPERDREJTE
        l_temp_res:=bs_mid_rate112(P_BRANCH_CODE, P_CURR_FIRST,P_CURR_LAST);
        if l_temp_res >0 then
          l_MID := l_temp_res;


          ELSE


select ccy1, ccy2
into L_MONEDHA_E_PARE,L_MONEDHA_E_DYTE
   from CYTMS_RATES
   Where BRANCH_CODE=P_BRANCH_CODE AND rate_type='STANDARD'and ccy2 = P_CURR_FIRST;
   --KY COUNTER ESHTE GJITHMONE TRUE POR NA DUHET QE TE HYJME NE ELSE
    if COUNTER5 > 0 then
            --FILLOJME KONTROLLOJME KU NDODHEN MONEDHAT
                 Select count(*) into COUNTER
   from CYTMS_RATES
   Where BRANCH_CODE=P_BRANCH_CODE AND CCY1=P_CURR_FIRST AND rate_type='STANDARD';

   IF COUNTER > 0 THEN --DMTH MONEDHA E PARE GJENDET NE KOLONEN E PARE
        Select CCY2 into TAB_L_MONEDHA_E_PARE
   from CYTMS_RATES
   Where BRANCH_CODE=P_BRANCH_CODE AND CCY1=P_CURR_FIRST AND rate_type='STANDARD';
      l_temp_res1 :=bs_mid_rate112(P_BRANCH_CODE, P_CURR_FIRST,TAB_L_MONEDHA_E_PARE);
      IF
      l_temp_res1 > 0 THEN-- DMTH U GJET
      -- KA DY RASTE TE TJERA MONEDHA E DYTE ESHTE NE KOLONEN E PARE OSE MONEDHA E DYTE ESHTE NE KOLONEN E DYTE
      --KONTROLLOJME KU ESHTE MONEDHA E DYTE
        Select count(*) into COUNTER1
   from CYTMS_RATES
   Where BRANCH_CODE=P_BRANCH_CODE AND CCY1=P_CURR_LAST AND rate_type='STANDARD';
   IF COUNTER1 > 0 THEN
     --DMTH MONEDHA E DYTE ESHTE NE KOLONEN E PARE
       Select CCY2 into TAB_L_MONEDHA_E_DYTE
   from CYTMS_RATES
   Where BRANCH_CODE=P_BRANCH_CODE AND CCY1=P_CURR_LAST
   AND rate_type='STANDARD';
      l_temp_res2 :=bs_mid_rate112(P_BRANCH_CODE, P_CURR_LAST,TAB_L_MONEDHA_E_DYTE);
      L_MID := L_TEMP_RES1 * L_TEMP_RES2;


     ELSE -- MONEDHA ESHTE NE KOLONEN E DYTE
            Select CCY1 into TAB_L_MONEDHA_E_DYTE
   from CYTMS_RATES
   Where BRANCH_CODE=P_BRANCH_CODE AND CCY2=P_CURR_LAST
   AND rate_type='STANDARD';
      l_temp_res2:=bs_mid_rate112(P_BRANCH_CODE
      ,TAB_L_MONEDHA_E_DYTE,P_CURR_LAST);
         L_MID := L_TEMP_RES1 * L_TEMP_RES2;--KJO FORMULE KA DAL NGA LLOG TE THJESHTA MES MARREDHENIEVE TE CURR
       END IF;-- MBAROJ PER RASTIN E PARE
        end if; --u llogarit


   ELSE --DMTH MONEDHA E PARE ESHTE NE KOLONEN E DYTE
          Select CCY1 into TAB_L_MONEDHA_E_PARE
   from CYTMS_RATES
   Where BRANCH_CODE=P_BRANCH_CODE AND CCY2=P_CURR_FIRST
   AND rate_type='STANDARD';
       l_temp_res1 :=bs_mid_rate112(P_BRANCH_CODE,TAB_L_MONEDHA_E_PARE, P_CURR_LAST);
      if    l_temp_res1 > 0 THEN-- DMTH U GJET
       -- KETU KEMI KURSIN E MONEDHES A PER TE CHECK MONEDHEN E DYTE KONTROLLOJME PRAPE NE CILEN KOLONE ESHTE
        Select count(*) into COUNTER1
   from CYTMS_RATES
   Where BRANCH_CODE=P_BRANCH_CODE AND CCY1=P_CURR_LAST AND rate_type='STANDARD';
   IF COUNTER1 > 0 THEN
     --DMTH MONEDHA E DYTE ESHTE NE KOLONEN E PARE
       Select CCY2 into TAB_L_MONEDHA_E_DYTE
   from CYTMS_RATES
   Where BRANCH_CODE=P_BRANCH_CODE AND CCY1=P_CURR_LAST
   AND rate_type='STANDARD';
      l_temp_res2:=bs_mid_rate112(P_BRANCH_CODE, P_CURR_LAST,TAB_L_MONEDHA_E_DYTE);
      L_MID := L_TEMP_RES1 * L_TEMP_RES2;

     ELSE -- MONEDHA ESHTE NE KOLONEN E DYTE
            Select CCY1 into TAB_L_MONEDHA_E_DYTE
   from CYTMS_RATES
   Where BRANCH_CODE=P_BRANCH_CODE AND CCY2=P_CURR_LAST
   AND rate_type='STANDARD';
      l_temp_res2:=bs_mid_rate112(P_BRANCH_CODE
      ,TAB_L_MONEDHA_E_DYTE,P_CURR_LAST);
         L_MID := L_TEMP_RES1 * L_TEMP_RES2;
       END IF;-- MBAROJ PER RASTIN E DYTE
 end if;--done
     END IF;--KEMI GJETUR VENDET E MONEDHAVE

     END IF;--MBARON GJETJA E MID
end if;
 RETURN L_MID;
 exception
  when others then
     dbms_output.put_line('KUJDES ME KALIMIN E VLERAVE');
     return 0;


       
          END;
